### ISSUE TITLE
Don't forget to add Vietnamese to the language overview

### ISSUE THREAD

**Issue by wilzbach** [dlang-tour/vietnamese#12]
https://tour.dlang.org/tour/en/welcome/languages

It's okay if it's not finished yet as it still might attract attention from other Vietnamese D developers.
Also asking on the NG for more manpower might help.

**Comment by icy** [comment]
Sorry for my late response. I've just noticed your ticket :) The PR is on the way https://github.com/dlang-tour/english/pull/272
