### ISSUE TITLE
Proof reading

### ISSUE THREAD

**Issue by icy** [dlang-tour/vietnamese#7]
Hi @wilzbach ,

@nhamlh from my city would help to review the translations. He is a devops engineer and would spend  time to review and raise questions from the point of view of a non-Dlang user :) Can you please help to allow him to approve the PR?

Thanks a lot.

**Comment by ZombineDev** [comment]
Hi @icy, I invited @nhamlh to the Vietnamese team. @nhamlh welcome aboard!
